title: Your awesome title
author: gaylord
email: sukdix@boob.com
description: > # this means to ignore newlines until "baseurl:"
  Check this shit out!  Best shit ever!

# social links
twitter_username: fuck bitches
github_username:  get money

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
